"""
PARWA Demo Knowledge Base Service

Manages pre-built industry knowledge bases and user uploads for the demo pack.
In production, uses pgvector for vector search over knowledge base documents.
For demo, uses in-memory storage with simulated search.
"""

import os
import uuid
from typing import Any, Dict, List, Optional
from datetime import datetime


# Pre-built industry knowledge bases
PREBUILT_KNOWLEDGE_BASES = [
    {
        'id': 'kb_ecommerce',
        'name': 'E-Commerce Support KB',
        'description': 'Order tracking, returns & refunds, product FAQs, shipping policies, payment issues.',
        'industry': 'ecommerce',
        'document_count': 47,
        'is_prebuilt': True,
    },
    {
        'id': 'kb_saas',
        'name': 'SaaS Technical Support KB',
        'description': 'API docs, billing FAQs, feature requests, account management, troubleshooting.',
        'industry': 'saas',
        'document_count': 62,
        'is_prebuilt': True,
    },
    {
        'id': 'kb_logistics',
        'name': 'Logistics & Shipping KB',
        'description': 'Shipment tracking, delivery management, warehouse queries, customs.',
        'industry': 'logistics',
        'document_count': 38,
        'is_prebuilt': True,
    },
    {
        'id': 'kb_healthcare',
        'name': 'Healthcare Support KB',
        'description': 'Appointments, insurance, medical records, prescriptions, billing.',
        'industry': 'healthcare',
        'document_count': 33,
        'is_prebuilt': True,
    },
    {
        'id': 'kb_realestate',
        'name': 'Real Estate Support KB',
        'description': 'Property inquiries, viewings, mortgages, tenant support, maintenance.',
        'industry': 'realestate',
        'document_count': 28,
        'is_prebuilt': True,
    },
    {
        'id': 'kb_restaurant',
        'name': 'Restaurant & Hospitality KB',
        'description': 'Reservations, menus, delivery, allergens, feedback.',
        'industry': 'restaurant',
        'document_count': 24,
        'is_prebuilt': True,
    },
]


class DemoKnowledgeBaseService:
    """Service for managing demo knowledge bases."""
    
    def __init__(self):
        self.uploaded_documents: Dict[str, Dict[str, Any]] = {}
        self.document_chunks: Dict[str, List[Dict[str, Any]]] = {}
    
    def list_prebuilt(self, industry: Optional[str] = None) -> List[Dict[str, Any]]:
        """List pre-built knowledge bases, optionally filtered by industry."""
        if industry:
            return [kb for kb in PREBUILT_KNOWLEDGE_BASES if kb['industry'] == industry]
        return PREBUILT_KNOWLEDGE_BASES
    
    def list_uploaded(self, industry: Optional[str] = None) -> List[Dict[str, Any]]:
        """List user-uploaded knowledge bases."""
        uploads = list(self.uploaded_documents.values())
        if industry:
            return [u for u in uploads if u.get('industry') == industry or not u.get('industry')]
        return uploads
    
    def upload_document(
        self,
        file_name: str,
        file_content: bytes,
        content_type: str,
        industry: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Process an uploaded document for the demo knowledge base.
        
        In production: chunk document, generate embeddings, store in pgvector.
        In demo: simulate chunking and return metadata.
        """
        doc_id = f"doc_{uuid.uuid4().hex[:8]}"
        chunks_count = max(1, len(file_content) // 500)
        
        doc = {
            'id': doc_id,
            'name': file_name,
            'content_type': content_type,
            'industry': industry or '',
            'size_bytes': len(file_content),
            'chunks_count': chunks_count,
            'is_prebuilt': False,
            'status': 'ready',
            'created_at': datetime.utcnow().isoformat(),
        }
        
        self.uploaded_documents[doc_id] = doc
        
        # Simulate chunks
        self.document_chunks[doc_id] = [
            {
                'chunk_id': f"{doc_id}_chunk_{i}",
                'content': f"Chunk {i+1} of {file_name}",
                'embedding': None,  # Would be generated by embedding model
            }
            for i in range(chunks_count)
        ]
        
        return doc
    
    def search(
        self,
        query: str,
        kb_ids: List[str],
        top_k: int = 5,
    ) -> List[Dict[str, Any]]:
        """
        Search knowledge bases for relevant content.
        
        In production: uses pgvector for vector similarity search.
        In demo: returns simulated results.
        """
        results = []
        
        for kb_id in kb_ids:
            # Check pre-built KBs
            prebuilt = next((kb for kb in PREBUILT_KNOWLEDGE_BASES if kb['id'] == kb_id), None)
            if prebuilt:
                results.append({
                    'kb_id': kb_id,
                    'kb_name': prebuilt['name'],
                    'relevance': 0.85,
                    'snippet': f"Relevant content from {prebuilt['name']} for query: {query[:50]}",
                })
            
            # Check uploaded documents
            doc = self.uploaded_documents.get(kb_id)
            if doc:
                results.append({
                    'kb_id': kb_id,
                    'kb_name': doc['name'],
                    'relevance': 0.72,
                    'snippet': f"Content from uploaded document {doc['name']} matching: {query[:50]}",
                })
        
        # Sort by relevance and return top_k
        results.sort(key=lambda x: x['relevance'], reverse=True)
        return results[:top_k]


# Singleton instance
demo_knowledge_base_service = DemoKnowledgeBaseService()
