"""
Jarvis Customer Care Models: post-onboarding persistence.

3 tables that persist the awareness, command, and alert data
that currently exists only in the LangGraph ParwaGraphState
TypedDict (GROUP 14 + GROUP 20). These tables make the state
queryable, auditable, and crash-resistant.

Tables:
  - jarvis_awareness_snapshots: Periodic snapshots of the 21-field
    GROUP 14 awareness state per CC session. The Awareness Engine
    (Phase 2) writes here on every tick. Dashboard reads latest
    snapshot for real-time monitoring.
  - jarvis_commands: Full audit log of every command Jarvis
    receives and executes. Maps to GROUP 20 fields. The Command
    Layer (Phase 3) writes here. Supports undo, replay, and
    compliance audit.
  - jarvis_proactive_alerts: Proactive alerts generated by the
    Awareness Engine. Dashboard displays these as toast/feed
    notifications. Distinct from messages because alerts are
    system-initiated, not user-initiated.

Design Decisions:
  - snapshot_type field on awareness_snapshots allows different
    tick intervals (periodic, on_change, manual, emergency)
  - Commands have a full lifecycle: received → parsed → executed
    → confirmed/failed, enabling rich status tracking
  - Alerts have severity + category for dashboard filtering
  - All tables FK to jarvis_sessions (cascade delete)
  - All tables have company_id for BC-001 tenant isolation
  - JSON columns for flexible data that maps directly from
    ParwaGraphState fields (avoiding schema changes when
    state fields are added)

BC-001: company_id first parameter, indexed on every table.
BC-008: Graceful degradation — null-safe columns.
BC-012: All timestamps UTC.
"""

from datetime import datetime, timezone

import uuid

from sqlalchemy import (
    Boolean, CheckConstraint, Column, DateTime, Float, Integer,
    Numeric, String, Text, ForeignKey, Index,
)
from sqlalchemy.orm import relationship

from database.base import Base


def _uuid() -> str:
    return str(uuid.uuid4())


# ── Enum-like value sets (used by CHECK constraints) ────────────

_SNAPSHOT_TYPES = "'periodic','on_change','manual','emergency'"
_COMMAND_INTENTS = "'query','control','configure','report','override'"
_COMMAND_STATUSES = (
    "'received','parsing','parsed','executing',"
    "'completed','failed','cancelled','undone'"
)
_ALERT_SEVERITIES = "'info','warning','critical','emergency'"
_ALERT_CATEGORIES = (
    "'system_health','ticket_volume','agent_pool',"
    "'quality','drift','billing','security','integration','training'"
)


# ══════════════════════════════════════════════════════════════════
# JARVIS AWARENESS SNAPSHOTS
# ══════════════════════════════════════════════════════════════════


class JarvisAwarenessSnapshot(Base):
    """Periodic snapshot of the 21-field GROUP 14 awareness state.

    The Awareness Engine (Phase 2) writes a snapshot on every tick.
    Each snapshot captures the full awareness picture at a point in
    time: plan status, system health, ticket volume, agent pool,
    training state, drift/quality metrics, and recent errors.

    This table replaces the ephemeral ParwaGraphState fields for
    persistence. The dashboard reads the latest snapshot for the
    real-time monitoring view. Historical snapshots enable trend
    analysis and retroactive debugging.

    Snapshot types:
      - periodic:  Automatic tick (e.g., every 30 seconds)
      - on_change: Written when a monitored field changes significantly
      - manual:    Triggered by user/admin action
      - emergency: Written when emergency_state changes
    """

    __tablename__ = "jarvis_awareness_snapshots"

    id = Column(String(36), primary_key=True, default=_uuid)
    session_id = Column(
        String(36),
        ForeignKey("jarvis_sessions.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    company_id = Column(
        String(36),
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )

    # ── Snapshot metadata ──
    snapshot_type = Column(String(20), nullable=False, default="periodic")
    tick_number = Column(Integer, nullable=True)
    # Monotonically increasing counter for this session's snapshots

    # ── GROUP 14 fields (flattened for queryability) ──

    # Plan & subscription
    current_plan = Column(String(20), nullable=True)
    plan_usage_today = Column(Numeric(5, 2), nullable=True)
    subscription_status = Column(String(20), nullable=True)
    days_until_renewal = Column(Integer, nullable=True)

    # System health
    system_health = Column(String(20), nullable=True)
    # healthy, degraded, critical, down
    channel_health_json = Column(Text, default="{}")
    # JSON: {"email": "healthy", "sms": "degraded", ...}

    # Alerts (summary counts; full alert details in jarvis_proactive_alerts)
    active_alerts_count = Column(Integer, default=0)
    active_alerts_json = Column(Text, default="[]")
    # JSON: [{"alert_id": "...", "severity": "warning", "message": "..."}]

    # Ticket volume
    ticket_volume_today = Column(Integer, default=0)
    ticket_volume_avg = Column(Numeric(10, 2), nullable=True)
    # 7-day rolling average
    ticket_volume_spike = Column(Boolean, default=False)

    # Agent pool
    active_agents = Column(Integer, default=0)
    agent_pool_capacity = Column(Integer, default=0)
    agent_pool_utilization = Column(Numeric(5, 2), nullable=True)
    # 0.0-100.0 percentage

    # Training (Agent Lightning)
    training_running = Column(Boolean, default=False)
    training_mistake_count = Column(Integer, default=0)
    training_model_version = Column(String(50), nullable=True)

    # Drift & quality
    drift_status = Column(String(20), nullable=True)
    # none, slight, moderate, severe
    drift_score = Column(Numeric(5, 4), nullable=True)
    # 0.0-1.0
    quality_score = Column(Numeric(5, 4), nullable=True)
    # 0.0-1.0
    quality_alerts_json = Column(Text, default="[]")
    # JSON: [{"metric": "...", "threshold": 0.8, "actual": 0.6, "severity": "warning"}]

    # Recent errors (last 5)
    last_5_errors_json = Column(Text, default="[]")
    # JSON: [{"error": "...", "node": "...", "timestamp": "...", "tenant_id": "..."}]

    # ── Raw state dump (for full recovery) ──
    raw_state_json = Column(Text, default="{}")
    # Complete ParwaGraphState GROUP 14 fields as JSON.
    # Used for crash recovery and debug replay.

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # ── Relationships ──
    session = relationship("JarvisSession", back_populates="awareness_snapshots")

    __table_args__ = (
        CheckConstraint(
            f"snapshot_type IN ({_SNAPSHOT_TYPES})",
            name="ck_jarvis_aware_snapshot_type",
        ),
        Index(
            "ix_jarvis_aware_comp_created",
            "company_id", "created_at",
        ),
        Index(
            "ix_jarvis_aware_session_created",
            "session_id", "created_at",
        ),
        {"schema": None},
    )


# ══════════════════════════════════════════════════════════════════
# JARVIS COMMANDS
# ══════════════════════════════════════════════════════════════════


class JarvisCommand(Base):
    """Full audit log of every command Jarvis receives and executes.

    Maps to GROUP 20 (JARVIS_COMMAND) fields in ParwaGraphState.

    Command lifecycle:
      1. received:  User sends natural language command
      2. parsing:   NL → structured command parsing in progress
      3. parsed:    Command successfully parsed with intent
      4. executing: Command is being executed
      5. completed: Command executed successfully
      6. failed:    Command execution failed
      7. cancelled: Command was cancelled (by user or system)
      8. undone:    Command was rolled back via undo

    The Command Layer (Phase 3) writes here at every lifecycle
    transition. This enables:
      - Full audit trail for compliance
      - Undo capability (last command can be reversed)
      - Command replay for debugging
      - Usage analytics (what commands are most common)
    """

    __tablename__ = "jarvis_commands"

    id = Column(String(36), primary_key=True, default=_uuid)
    session_id = Column(
        String(36),
        ForeignKey("jarvis_sessions.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    company_id = Column(
        String(36),
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )

    # ── Raw input ──
    raw_input = Column(Text, nullable=False)
    # The natural language command as typed by the user
    source = Column(String(20), nullable=False, default="chat")
    # chat, api, co_pilot, proactive, scheduled

    # ── Parsed command (GROUP 20 mapping) ──
    command_parsed = Column(Text, nullable=True)
    # Structured representation of the parsed command
    command_intent = Column(String(20), nullable=True)
    # query, control, configure, report, override
    confidence = Column(Numeric(5, 4), nullable=True)
    # 0.0-1.0 confidence in parsing

    # ── Co-Pilot context ──
    co_pilot_suggestion = Column(Text, nullable=True)
    co_pilot_suggestion_type = Column(String(50), nullable=True)
    # response_template, escalation_hint, knowledge_link, policy_reminder

    # ── Execution ──
    status = Column(String(15), nullable=False, default="received")
    result_json = Column(Text, default="{}")
    # Execution result data
    error_message = Column(Text, nullable=True)
    # Error message if status=failed

    # ── Metadata ──
    command_metadata_json = Column(Text, default="{}")
    # {parsed_at, execution_time_ms, tokens_used, ...}
    undo_available = Column(Boolean, default=False)
    # Whether this command can be undone
    undone_by_command_id = Column(
        String(36),
        nullable=True,
    )
    # If this command was undone, link to the undo command

    # ── Timestamps ──
    received_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    parsed_at = Column(DateTime, nullable=True)
    executed_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # ── Relationships ──
    session = relationship("JarvisSession")

    __table_args__ = (
        CheckConstraint(
            f"command_intent IN ({_COMMAND_INTENTS})",
            name="ck_jarvis_cmd_intent",
        ),
        CheckConstraint(
            f"status IN ({_COMMAND_STATUSES})",
            name="ck_jarvis_cmd_status",
        ),
        CheckConstraint(
            f"source IN ('chat','api','co_pilot','proactive','scheduled')",
            name="ck_jarvis_cmd_source",
        ),
        Index(
            "ix_jarvis_cmd_comp_created",
            "company_id", "created_at",
        ),
        Index(
            "ix_jarvis_cmd_session_created",
            "session_id", "created_at",
        ),
        Index(
            "ix_jarvis_cmd_comp_status",
            "company_id", "status",
        ),
        {"schema": None},
    )


# ══════════════════════════════════════════════════════════════════
# JARVIS PROACTIVE ALERTS
# ══════════════════════════════════════════════════════════════════


class JarvisProactiveAlert(Base):
    """Proactive alerts generated by the Awareness Engine.

    Unlike JarvisMessage (which is user-initiated), proactive alerts
    are system-initiated. The Awareness Engine detects an issue
    (ticket spike, quality drop, drift, emergency) and creates an
    alert that appears on the CC dashboard as a toast or feed entry.

    Alerts have a lifecycle:
      - active:   Visible on dashboard, not yet acknowledged
      - acknowledged: User has seen the alert
      - dismissed: User dismissed the alert
      - resolved: Underlying issue has been resolved
      - expired:  Alert TTL has passed

    Alert severity drives dashboard behavior:
      - info:       Blue toast, auto-dismiss after 30s
      - warning:    Yellow toast, persists until acknowledged
      - critical:   Orange banner, requires acknowledgment
      - emergency:  Red modal, blocks until resolved
    """

    __tablename__ = "jarvis_proactive_alerts"

    id = Column(String(36), primary_key=True, default=_uuid)
    session_id = Column(
        String(36),
        ForeignKey("jarvis_sessions.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    company_id = Column(
        String(36),
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )

    # ── Alert identification ──
    alert_type = Column(String(50), nullable=False)
    # ticket_volume_spike, quality_drop, drift_detected,
    # agent_pool_exhausted, emergency_state_change,
    # budget_threshold, training_complete, integration_failure
    severity = Column(String(15), nullable=False, default="info")
    # info, warning, critical, emergency
    category = Column(String(30), nullable=False, default="system_health")
    # system_health, ticket_volume, agent_pool, quality,
    # drift, billing, security, integration

    # ── Alert content ──
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    # Human-readable alert description
    details_json = Column(Text, default="{}")
    # Structured alert details for dashboard rendering:
    # {metric, threshold, actual, trend, recommendation}

    # ── Alert lifecycle ──
    status = Column(String(15), nullable=False, default="active")
    # active, acknowledged, dismissed, resolved, expired
    acknowledged_by = Column(String(36), nullable=True)
    # user_id who acknowledged
    acknowledged_at = Column(DateTime, nullable=True)
    resolved_at = Column(DateTime, nullable=True)

    # ── Dashboard behavior ──
    action_required = Column(Boolean, default=False)
    # Whether user action is needed to resolve
    action_url = Column(String(500), nullable=True)
    # Deep link to the relevant dashboard section
    ttl_seconds = Column(Integer, default=0)
    # Time-to-live in seconds (0 = no expiry)

    # ── Related resources ──
    related_snapshot_id = Column(String(36), nullable=True)
    # FK to jarvis_awareness_snapshots.id (not enforced — snapshots
    # may be pruned while alerts are kept)
    related_command_id = Column(String(36), nullable=True)
    # FK to jarvis_commands.id if alert triggered a command

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # ── Relationships ──
    session = relationship("JarvisSession", back_populates="proactive_alerts")

    __table_args__ = (
        CheckConstraint(
            f"severity IN ({_ALERT_SEVERITIES})",
            name="ck_jarvis_alert_severity",
        ),
        CheckConstraint(
            f"category IN ({_ALERT_CATEGORIES})",
            name="ck_jarvis_alert_category",
        ),
        CheckConstraint(
            f"status IN ('active','acknowledged','dismissed','resolved','expired')",
            name="ck_jarvis_alert_status",
        ),
        Index(
            "ix_jarvis_alert_comp_created",
            "company_id", "created_at",
        ),
        Index(
            "ix_jarvis_alert_comp_severity",
            "company_id", "severity",
        ),
        Index(
            "ix_jarvis_alert_session_created",
            "session_id", "created_at",
        ),
        Index(
            "ix_jarvis_alert_comp_status",
            "company_id", "status",
        ),
        {"schema": None},
    )
