"""
Shadow Mode Models: shadow_log, shadow_preferences.

Plus shadow queue tables for channel interceptors:
- EmailShadowQueue: Holds outbound emails awaiting approval
- SmsShadowQueue: Holds outbound SMS messages awaiting approval
- ChatShadowQueue: Holds outbound chat messages awaiting approval

Dual-control system that allows AI actions to be executed in shadow mode
(observation only), supervised (requires manager approval), or graduated
(auto-approved based on confidence).

BC-001: Every table has company_id.
"""

from datetime import datetime

import uuid

from sqlalchemy import (
    Column, String, Float, Text, DateTime, ForeignKey,
    UniqueConstraint, Index, Boolean, Integer,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.sql import func

from database.base import Base


def _uuid() -> str:
    return str(uuid.uuid4())


class ShadowLog(Base):
    __tablename__ = "shadow_log"

    id = Column(String(36), primary_key=True, default=_uuid)
    company_id = Column(
        String(36),
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    # Action type: 'refund', 'sms_reply', 'email_reply', etc.
    action_type = Column(String(50), nullable=False)
    # Full action payload (JSONB for flexible schema)
    action_payload = Column(JSONB, nullable=False, default=dict)
    # Risk score computed by Jarvis heuristic engine (0.0 to 1.0)
    jarvis_risk_score = Column(Float, nullable=True)
    # Execution mode: shadow / supervised / graduated
    mode = Column(String(15), nullable=False, default="supervised")
    # Manager decision: approved / rejected / modified / null
    manager_decision = Column(String(15), nullable=True)
    manager_note = Column(Text, nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.utcnow(),
        nullable=False,
    )

    __table_args__ = (
        Index("idx_shadow_log_company", "company_id", created_at.desc()),
        Index("idx_shadow_log_mode", "mode", "manager_decision"),
    )


class ShadowPreference(Base):
    __tablename__ = "shadow_preferences"

    id = Column(String(36), primary_key=True, default=_uuid)
    company_id = Column(
        String(36),
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Action category: 'refund', 'sms', 'email_reply', etc.
    action_category = Column(String(50), nullable=False)
    # Preferred mode for this category: shadow / supervised / graduated
    preferred_mode = Column(String(15), nullable=False, default="shadow")
    # How this preference was set: 'ui' or 'jarvis'
    set_via = Column(String(10), nullable=False, default="ui")
    updated_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.utcnow(),
        onupdate=lambda: datetime.utcnow(),
        nullable=False,
    )

    __table_args__ = (
        UniqueConstraint(
            "company_id", "action_category",
            name="uq_shadow_prefs_company_category",
        ),
        Index("idx_shadow_prefs_company", "company_id"),
    )


class EmailShadowQueue(Base):
    """Shadow Mode Email Queue.

    Holds outbound emails generated by AI when the company is in
    SHADOW or SUPERVISED mode, awaiting manager approval.

    Flow:
    1. AI generates email draft → held in this queue
    2. Manager reviews in dashboard
    3. Manager approves/rejects/modifies
    4. On approve: email sent via Brevo, record updated
    5. On reject: record marked as rejected

    BC-001: Scoped to company_id.
    """
    __tablename__ = "email_shadow_queue"

    id = Column(String(36), primary_key=True, default=_uuid)
    company_id = Column(
        String(36),
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    shadow_log_id = Column(
        String(36),
        ForeignKey("shadow_log.id", ondelete="CASCADE"),
        nullable=True, index=True,
    )
    # Email details
    to_address = Column(String(255), nullable=False)
    cc_addresses = Column(Text, nullable=True)
    bcc_addresses = Column(Text, nullable=True)
    subject = Column(String(500), nullable=False)
    body_text = Column(Text, nullable=True)
    body_html = Column(Text, nullable=True)
    from_address = Column(String(255), nullable=True)
    reply_to = Column(String(255), nullable=True)
    # Related entities
    ticket_id = Column(
        String(36),
        ForeignKey("tickets.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )
    template_id = Column(String(36), nullable=True)
    template_data = Column(JSONB, nullable=True, default=dict)
    attachments = Column(JSONB, nullable=True, default=list)
    # Status tracking
    status = Column(String(20), nullable=False, default="pending")  # pending/approved/rejected/sent/failed
    message_id = Column(String(255), nullable=True)  # Brevo message ID
    sent_at = Column(DateTime(timezone=True), nullable=True)
    error_message = Column(Text, nullable=True)

    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.utcnow(),
        nullable=False,
    )
    updated_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.utcnow(),
        onupdate=lambda: datetime.utcnow(),
        nullable=False,
    )

    __table_args__ = (
        Index("idx_email_shadow_company_status", "company_id", "status"),
        Index("idx_email_shadow_log", "shadow_log_id"),
    )

    def to_dict(self) -> dict:
        """Serialize for API responses."""
        return {
            "id": self.id,
            "company_id": self.company_id,
            "shadow_log_id": self.shadow_log_id,
            "to_address": self.to_address,
            "cc_addresses": self.cc_addresses,
            "bcc_addresses": self.bcc_addresses,
            "subject": self.subject,
            "body_text": self.body_text,
            "body_html": self.body_html,
            "from_address": self.from_address,
            "reply_to": self.reply_to,
            "ticket_id": self.ticket_id,
            "template_id": self.template_id,
            "template_data": self.template_data,
            "attachments": self.attachments,
            "status": self.status,
            "message_id": self.message_id,
            "sent_at": self.sent_at.isoformat() if self.sent_at else None,
            "error_message": self.error_message,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


class SmsShadowQueue(Base):
    """Shadow Mode SMS Queue.

    Holds outbound SMS messages generated by AI when the company is in
    SHADOW or SUPERVISED mode, awaiting manager approval.

    Flow:
    1. AI generates SMS draft → held in this queue
    2. Manager reviews in dashboard
    3. Manager approves/rejects/modifies
    4. On approve: SMS sent via Twilio, record updated
    5. On reject: record marked as rejected

    BC-001: Scoped to company_id.
    BC-010: TCPA compliance - respects opt-out status.
    BC-006: Rate limiting - max 5 per thread per 24 hours.
    """
    __tablename__ = "sms_shadow_queue"

    id = Column(String(36), primary_key=True, default=_uuid)
    company_id = Column(
        String(36),
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    shadow_log_id = Column(
        String(36),
        ForeignKey("shadow_log.id", ondelete="CASCADE"),
        nullable=True, index=True,
    )
    # SMS details
    to_number = Column(String(20), nullable=False)
    from_number = Column(String(20), nullable=True)
    message = Column(Text, nullable=False)
    # Related entities
    ticket_id = Column(
        String(36),
        ForeignKey("tickets.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )
    media_urls = Column(JSONB, nullable=True, default=list)
    # Status tracking
    status = Column(String(20), nullable=False, default="pending")  # pending/approved/rejected/sent/failed
    message_sid = Column(String(100), nullable=True)  # Twilio SID
    sent_at = Column(DateTime(timezone=True), nullable=True)
    error_code = Column(String(20), nullable=True)
    error_message = Column(Text, nullable=True)

    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.utcnow(),
        nullable=False,
    )
    updated_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.utcnow(),
        onupdate=lambda: datetime.utcnow(),
        nullable=False,
    )

    __table_args__ = (
        Index("idx_sms_shadow_company_status", "company_id", "status"),
        Index("idx_sms_shadow_log", "shadow_log_id"),
        Index("idx_sms_shadow_to_number", "to_number"),
    )

    def to_dict(self) -> dict:
        """Serialize for API responses."""
        return {
            "id": self.id,
            "company_id": self.company_id,
            "shadow_log_id": self.shadow_log_id,
            "to_number": self.to_number,
            "from_number": self.from_number,
            "message": self.message,
            "ticket_id": self.ticket_id,
            "media_urls": self.media_urls,
            "status": self.status,
            "message_sid": self.message_sid,
            "sent_at": self.sent_at.isoformat() if self.sent_at else None,
            "error_code": self.error_code,
            "error_message": self.error_message,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


class ChatShadowQueue(Base):
    """Shadow Mode Chat Queue.

    Holds outbound chat widget messages generated by AI when the company is
    in SHADOW or SUPERVISED mode, awaiting manager approval.

    Flow:
    1. AI generates chat response → held in this queue
    2. Manager reviews in dashboard
    3. Manager approves/rejects/edits
    4. On approve: message sent via chat widget, record updated
    5. On reject: record marked as rejected

    BC-001: Scoped to company_id.
    """
    __tablename__ = "chat_shadow_queue"

    id = Column(String(36), primary_key=True, default=_uuid)
    company_id = Column(
        String(36),
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    shadow_log_id = Column(
        String(36),
        ForeignKey("shadow_log.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Chat session details
    session_id = Column(String(100), nullable=False)
    conversation_id = Column(String(36), ForeignKey("conversations.id"), nullable=True)
    # Message details
    message_text = Column(Text, nullable=False)
    message_type = Column(String(20), default="text")  # text, card, carousel, etc.
    attachments = Column(JSONB, nullable=True)  # List of attachment metadata
    quick_replies = Column(JSONB, nullable=True)  # Quick reply options
    # Customer info
    customer_id = Column(String(36), ForeignKey("customers.id"), nullable=True)
    visitor_id = Column(String(100), nullable=True)  # For anonymous visitors
    # AI metadata
    suggested_response = Column(Text, nullable=True)  # Original AI suggestion
    confidence_score = Column(String(10), nullable=True)  # AI confidence level
    # Status tracking
    status = Column(String(20), nullable=False, default="pending")
    # pending, approved, rejected, sent, failed
    approved_by = Column(String(36), ForeignKey("users.id"), nullable=True)
    approved_at = Column(DateTime(timezone=True), nullable=True)
    rejection_reason = Column(Text, nullable=True)
    sent_at = Column(DateTime(timezone=True), nullable=True)
    message_uuid = Column(String(100), nullable=True)  # Chat message UUID
    error_message = Column(Text, nullable=True)
    # Edit tracking
    was_edited = Column(Boolean, default=False)
    original_message = Column(Text, nullable=True)  # Before manager edit
    edited_message = Column(Text, nullable=True)  # Manager's edited version
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.utcnow(),
        nullable=False,
    )
    updated_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.utcnow(),
        onupdate=lambda: datetime.utcnow(),
        nullable=False,
    )

    __table_args__ = (
        Index("idx_chat_shadow_queue_company_status", "company_id", "status"),
        Index("idx_chat_shadow_queue_session", "session_id"),
        Index("idx_chat_shadow_queue_created", "created_at"),
    )

    def to_dict(self) -> dict:
        """Serialize for API responses."""
        return {
            "id": self.id,
            "company_id": self.company_id,
            "shadow_log_id": self.shadow_log_id,
            "session_id": self.session_id,
            "conversation_id": self.conversation_id,
            "message_text": self.message_text,
            "message_type": self.message_type,
            "customer_id": self.customer_id,
            "visitor_id": self.visitor_id,
            "suggested_response": self.suggested_response,
            "confidence_score": self.confidence_score,
            "status": self.status,
            "approved_by": self.approved_by,
            "approved_at": self.approved_at.isoformat() if self.approved_at else None,
            "rejection_reason": self.rejection_reason,
            "sent_at": self.sent_at.isoformat() if self.sent_at else None,
            "message_uuid": self.message_uuid,
            "error_message": self.error_message,
            "was_edited": self.was_edited,
            "original_message": self.original_message,
            "edited_message": self.edited_message,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
