apiVersion: v1
kind: LimitRange
metadata:
  name: parwa-limits
  namespace: parwa
  labels:
    app.kubernetes.io/name: parwa
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: parwa-platform
spec:
  limits:
    - type: Container
      default:
        cpu: 100m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      max:
        cpu: "2"
        memory: 2Gi
      min:
        cpu: 10m
        memory: 32Mi
