apiVersion: v1
kind: ResourceQuota
metadata:
  name: parwa-quota
  namespace: parwa
  labels:
    app.kubernetes.io/name: parwa
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: parwa-platform
spec:
  hard:
    limits.cpu: "20"
    limits.memory: 40Gi
    pods: "50"
    services: "20"
    persistentvolumeclaims: "20"
